name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Extract and Find Project
      run: |
        unzip *.zip -d project_folder
        # البحث عن المجلد الذي يحتوي على gradlew والانتقال إليه
        GRADLE_DIR=$(find project_folder -name gradlew -exec dirname {} \;)
        echo "Project directory found at: $GRADLE_DIR"
        cd "$GRADLE_DIR"
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Finished-APK
        path: "**/build/outputs/apk/debug/*.apk"
